services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./docker/mongodb/init.d/:/docker-entrypoint-initdb.d/:ro
      - mongodb-data:/data/db/
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_SHOULD_VALIDATE_COLLECTIONS=${MONGO_SHOULD_VALIDATE_COLLECTIONS}
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
    driver: local
    name: mongodb-data
